#cloud-config
write_files:
  - path: /etc/sysconfig/docker-storage-setup
    permissions: 0644
    owner: root
    content: |
        GROWPART=true
        ROOT_SIZE=+100%FREE
        STORAGE_DRIVER=overlay2